package LootlyBackend.utils;

public enum DiscountType {
    HOLIDAY,
    BLACK_FRIDAY,
    CYBER_MONDAY,
    EID,
    BACK_TO_SCHOOL,
    VALENTINES_DAY,
    ANNIVERSARY,
    FESTIVE,
    SUMMER_SALE,
    WINTER_SALE,
    SEASONAL_CLEARANCE,
    CHRISTMAS_SALE,
    SPRING_SALE,
    FLASH_SALE,
    THANKSGIVING_SALE,
    MOTHERS_DAY,
    FATHERS_DAY
}
